# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6e3dc5bb68c682e48360be75892588fd196a4778844ff1f8909ae1cb32a90c1771845d9f23423f4b08f6f09c10bc95df0a8e39ccc4a398d05da077d6a8aaf596

test:
  secret_key_base: 54b84edb661674d7f183758dfe08a271ea2863cbb174376a87d2a65e5f9df824220e88adce42cecce14d59d27b4eab883ba493ec5ae5830654de225010656f62

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
